let x = document.getElementById("ListfiveNYCstartupsyoudlovetoworkat - 25");
let y = x.childNodes;
let companiesArray=[];
for(let i=0;i<y.length;i++){

if(y[i].innerHTML!=undefined){
companiesArray.push(y[i].innerHTML);

}
}

console.log(companiesArray);

let copiedObject = [
    "Adcade",
    "AI.Reverie",
    "AppNexus",
    "Aprizi",
    "Artsy",
    "Aviary",
    "Babbel",
    "BankSimple",
    "Barkbox",
    "Betterpath",
    "Birchbox",
    "bitly",
    "Blockstack",
    "bloglovin",
    "BlueCore",
    "boardrounds",
    "Boxee",
    "Branch",
    "Brewster",
    "Business Insider",
    "buzzd",
    "BuzzFeed",
    "Cafe",
    "Canary",
    "Canvas",
    "Cardstack",
    "Carve Systems",
    "Celmatix",
    "Challenge Post",
    "Chartbeat",
    "ChatID",
    "CitiBike",
    "Clarifai",
    "ClassPass",
    "Clothia",
    "Codecademy",
    "Comixology",
    "Cover",
    "Crowdtap",
    "Datadog",
    "DesignerPages",
    "Dia &amp; Co",
    "Eight Sleep",
    "Etsy",
    "First Look Media",
    "Flatiron",
    "Foursquare",
    "frid.ge",
    "GetGlue",
    "Gilt",
    "Giphy",
    "GIPHY",
    "GroupMe",
    "Hunch",
    "hyperpublic",
    "Instapaper",
    "Intent Media",
    "Jigsaw",
    "Jiko Technologies",
    "JW Player",
    "Kensho",
    "Kickstarter",
    "kikin",
    "Knewton",
    "Knodes",
    "Knotch",
    "Kollabora",
    "Lifebooker",
    "Local Response",
    "Lua Technologies",
    "Magnetic",
    "Major League Hacking",
    "MakeSpace",
    "Mashable",
    "Matchbook",
    "MedicaSafe",
    "Meetup",
    "MongoDB",
    "Mount Sinai",
    "Nestio",
    "Next Jump",
    "Numberfire",
    "Oden Technologies",
    "Offerpop",
    "OKCupid",
    "OMGPop",
    "Ordr.in",
    "Oscar",
    "Oyster",
    "Paribus",
    "Parse.ly",
    "Plated",
    "Point",
    "ProPublica",
    "QLabs",
    "REDI",
    "RentTheRunway",
    "Sailthru",
    "Salido",
    "SeamlessDocs",
    "Second Market",
    "Seen",
    "Shapeways",
    "SinglePlatform",
    "Skillshare",
    "SocialFlow",
    "Socratic",
    "SpotOn",
    "Tapad",
    "Teleport",
    "Thinkful",
    "Thrillist",
    "Tilt / Windmill",
    "Trendalytics",
    "Trendrr",
    "Tumblr",
    "Two Bulls",
    "Ufora",
    "Venmo",
    "Vericred",
    "Vostu",
    "Wellthy",
    "Wildcard",
    "Xtify",
    "Yipit",
    "YouNow",
    "Other"
];